### ISSUE TITLE
Feature: disable auto-detect for wallets 

### ISSUE THREAD

**Issue by dogebonker** [anza-xyz/wallet-adapter#989]
**Is your feature request related to a problem? Please describe.**
In my dapp I want to strictly disallow users to connect certain wallets, it's not possible if I just use the default package without modifications.

**Describe the solution you'd like**
Would it be possible to add a flag to `<WalletProvider />` so that we would only show wallets which are passed as a `wallet` prop?

**Comment by mcintyre94** [comment]
I don't think this is really possible with wallet-standard wallets, because nothing stops a wallet being injected with an arbitrary name/icon etc and impersonating one of the wallets you whitelisted. There's no way for your app to verify [any of the fields of the `Wallet` type](https://github.com/wallet-standard/wallet-standard/blob/ba5c16b7f608754ff5c494079f6b7549b857c390/packages/core/base/src/wallet.ts#L34).

Whereas with adapters only the wallets you included would be detected, so this was the behaviour you'd get. 

We wouldn't ship a version of wallet-adapter, or an option, which removes wallet-standard wallets. Our messaging to wallets is that this is the API to use, and newer wallets like Backpack don't have an adapter because they've never needed one. 

I also don't think we'd want to ship an option to eg filter by wallet names, because that could mislead apps into thinking it's more effective than it can be with wallet-standard wallets.

**Comment by glitch-txs** [comment]
>I don't think this is really possible with wallet-standard wallets, because nothing stops a wallet being injected with an arbitrary name/icon etc and impersonating one of the wallets you whitelisted. There's no way for your app to verify [any of the fields of the Wallet type](https://github.com/wallet-standard/wallet-standard/blob/ba5c16b7f608754ff5c494079f6b7549b857c390/packages/core/base/src/wallet.ts#L34).

in EIP-6963 we added uuid and rdns for this reason partially.
